---
- hosts: windows 
  vars:
    flavor:  "{{FLAVOR|default('watson')}}"
    ver_no:  "{{VER|default('4.5.0')}}"
    build_no:  "{{BUILD_NO|default(2601)}}"
    base_url:  http://172.23.120.24/builds/latestbuilds/couchbase-server/{{flavor}}/
    build_pkg:  "couchbase-server-enterprise_{{ver_no}}-{{build_no}}-windows_amd64.exe"
    url_var: "{{base_url}}/{{build_no}}/{{build_pkg}}"
    build_url: "{{URL|default(url_var)}}"
  tasks:
  - name: copy wget 
    win_copy: src=wget.exe dest=c:/wget.exe
  - name: download 
    raw: "c:/wget.exe --no-check-certificate -q {{build_url}} -O c:/couchbase.exe"
  - name: copy iss
    win_copy: src=install_{{ver_no}}.iss dest=c:/install.iss
  - name: install 
    raw: "c:/couchbase.exe /s -f1c:/install.iss"

