---
- hosts: couchbaseservers
  vars:
    build_no:  "{{BUILD_NO|default(754)}}"
    base_url:  http://172.23.120.24/builds/latestbuilds/couchbase-server/watson/
    build_pkg:  "couchbase-server-enterprise_4.5.0-{{build_no}}-ubuntu14.04_amd64.deb"
    build_url: "{{base_url}}/{{build_no}}/{{build_pkg}}"
    deb_path: "/tmp/{{build_pkg}}"
  tasks:
  - name: rm 
    win_file: path=D:\data state=absent
