---
- hosts: centos
  remote_user: root
  tasks:
  - name: rm locks
    shell: "rm /var/lib/dpkg/lock"
    ignore_errors: True
  - name: rm front end locks
    shell: "rm /var/lib/dpkg/lock-frontend"
    ignore_errors: True
  - name: configure
    shell: "dpkg --configure -a"
  - name: stop couchbase
    shell: "ps aux | grep 'couchbase' | awk '{print $2}' | xargs kill -s 9"
    ignore_errors: True
  - name: stop memcached
    shell: "ps aux | grep 'memcached' | awk '{print $2}' | xargs kill -s 9"
    ignore_errors: True
  - name: stop epmd
    shell: "ps aux | grep 'epmd' | awk '{print $2}' | xargs kill -s 9"
    ignore_errors: True
  - name: uninstall couchbase
    apt: name=couchbase-server state=absent
  - name: rm opt dir
    shell: "rm -rf /opt/couchbase"
  - name: rm data dir
    shell: "rm -rf /data/*"
  - name: rm config profile
    shell: "rm -rf /etc/couchbase.d/*"
  - name: stop couchbase
    shell: "ps aux | grep 'couchbase' | awk '{print $2}' | xargs kill -s 9"
    ignore_errors: True
  - name: stop memcached
    shell: "ps aux | grep 'memcached' | awk '{print $2}' | xargs kill -s 9"
    ignore_errors: True
  - name: stop epmd
    shell: "ps aux | grep 'epmd' | awk '{print $2}' | xargs kill -s 9"
    ignore_errors: True

# Remove sync_gateway
- hosts: syncgateways
  become: yes
  tasks:
  # Stop sync_gateway service
  - name: SYNC GATEWAY | Stop sync_gateway service
    service: name=sync_gateway state=stopped
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian" or ansible_distribution == "MacOSX"
    ignore_errors: yes

  - name: SYNC GATEWAY | Stop sync_gateway
    shell: /sbin/initctl stop sync_gateway
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or ansible_distribution == "RedHat" or ansible_distribution == "Amazon"
    ignore_errors: yes

    # Remove sync_gateway package
  - name: SYNC GATEWAY | Uninstall sync_gateway rpm
    shell: rpm -e couchbase-sync-gateway
    ignore_errors: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

    # Remove sync_gateway package
  - name: SYNC GATEWAY | Uninstall sync_gateway deb
    shell: dpkg -r couchbase-sync-gateway
    ignore_errors: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    # Remove sync_gateway service
  - name: SYNC GATEWAY | Remove sync_gateway service
    file: path=/usr/lib/systemd/system/sync_gateway.service state=absent
    ignore_errors: yes

    # Delete sync_gateway binary
  - name: SYNC GATEWAY | Delete sync_gateway binary
    become: yes
    file: path=/opt/couchbase-sync-gateway state=absent
    ignore_errors: yes

    # Remove sync gateway source
  - name: SYNC GATEWAY | Remove sync gateway source
    shell: rm -rf /home/centos/*
    ignore_errors: yes

  - name: SYNC GATEWAY | Remove sync gateway source .repo directory
    shell: rm -rf /home/centos/.repo
    ignore_errors: yes

  - name: SYNC GATEWAY | Remove tmp logging dir (log rotation tests)
    shell: rm -rf /tmp/sg_logs
    ignore_errors: yes

  - name: SYNC GATEWAY | Remove sync_gateway user on Centos
    user: name=sync_gateway state=absent remove=yes force=yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  # Check no sync_gateways or accels running
  - name: SYNC GATEWAY | verify no service on 4985
    wait_for: port=4985 delay=1 state=stopped
