---
- hosts: couchbaseservers
  vars:
    build_no:  "{{BUILD_NO|default(1896)}}"
    base_url:  http://latestbuilds.hq.couchbase.com/
    build_pkg:  "couchbase_server-enterprise-windows-amd64-3.1.6-{{build_no}}.exe"
    build_url: "{{base_url}}/{{build_pkg}}"
  tasks:
  - name: copy wget 
    win_copy: src=wget.exe dest=c:/wget.exe
  - name: download 
    raw: "c:/wget.exe --no-check-certificate -q {{build_url}} -O c:/couchbase.exe"
  - name: copy iss
    win_copy: src=install_3.1.6.iss dest=c:/install.iss
  - name: install 
    raw: "c:/couchbase.exe /s -f1c:/install.iss"

