- hosts: centos3
  vars:
    ver_no: "{{VER|default('4.5.0')}}"
  remote_user: root
  tasks:
  - name: remove systemd-timesyncd
    apt:
      name: systemd-timesyncd
      state: absent

  - name: install ntp
    apt:
      name: ntp

  - name: stop ntpd service
    service:
      name: ntpd
      state: stopped

  - name: sync time
    shell: "ntpd -gq"

  - name: start ntpd service
    service:
      name: ntpd
      state: started